# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  locale: en-us
  title: "HZ Lab"
  params:
    description: We focus on waterfowl genetics, breeding, and molecular improvement, with research spanning genetic resources, genetic mechanisms, genomics, and precision breeding. Our work aims to elucidate the genetic basis of economically important traits and to develop innovative technologies and approaches for waterfowl breeding.
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Research
        url: /research/
        weight: 20
      - name: Publications
        url: /publications/
        weight: 30
      - name: People
        url: /people/
        weight: 40
      - name: Resources
        url: /resources/
        weight: 50
      - name: News
        url: /blog/
        weight: 60
      - name: Join Us
        url: /join/
        weight: 70
      - name: Contact
        url: /contact/
        weight: 80